# cinephoria-web/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

EXPOSE 4200

# Le code sera monté via volume pour le hot-reload
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll=2000"]
